- id: doi:10.1038/s41598-025-91430-0
  type: paper
  description: Teach-Former, a novel knowledge distillation (KD) framework that leverages a Transformer backbone to effectively condense the knowledge of multiple teacher models into a single, streamlined student model. Moreover, it excels in the contextual and spatial interpretation of relationships across multimodal images for more accurate and precise segmentation.
  date: '2025-05-07'
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41598-025-91430-0/MediaObjects/41598_2025_91430_Fig2_HTML.png?as=webp
  buttons:
  - type: github
    link: https://github.com/FarihaHossain/TeachFormer
  - type: source
    text: Manuscript Source
    link: https://www.nature.com/articles/s41598-025-91430-0
  tags:
  - knowledge distillation
  - oncology
  repo: FarihaHossain/TeachFormer

- id: doi:10.1007/978-3-031-43990-2_65
  type: paper
  buttons:
  - type: github
    link: https://github.com/FarihaHossain/SwinFSR
  repo: FarihaHossain/SwinFSR

- id: doi:10.1109/isbi53787.2023.10230342
  type: paper
  buttons:
  - type: github
    link: https://github.com/FarihaHossain/Swin-SFTNet
  repo: FarihaHossain/Swin-SFTNet

- id: doi:10.1007/978-3-031-17721-7_8
  type: paper
  buttons:
  - type: github
    link: https://github.com/FarihaHossain/ECG-ATK-GAN
  repo: FarihaHossain/ECG-ATK-GAN

- id: doi:10.1109/icmla52953.2021.00016
  type: paper
  buttons:
  - type: github
    link: https://github.com/FarihaHossain/ECG-Adv-GAN
  repo: FarihaHossain/ECG-Adv-GAN

- id: doi:10.1007/978-3-031-20716-7_29
  type: paper
  buttons:
  - type: github
    link: https://github.com/FarihaHossain/Game-Theoretical-vulnerability-analysis-of-Adversarial-Attack
  repo: FarihaHossain/Game-Theoretical-vulnerability-analysis-of-Adversarial-Attack

- id: doi:10.1007/978-3-031-16525-2_3
  type: paper

- id: doi:10.1109/iccvw54120.2021.00362
  type: paper

- id: doi:10.1007/978-3-030-87237-3_4
  type: paper

- id: doi:10.1109/icpr48806.2021.9412428
  type: paper

- id: doi:10.1007/978-3-030-64559-5_10
  type: paper

- id: doi:10.1038/s41598-020-78696-2
  type: paper

- id: doi:10.1038/s41526-024-00364-w
  type: paper

- id: doi:10.1016/j.xops.2024.100493
  type: paper

- id: doi:10.1016/j.xpro.2022.101852
  type: paper

- id: doi:10.1016/j.isci.2022.104277
  type: paper

- type: paper
  title: Detecting spaceflight associated neuro-ocular syndrome (SANS) using light-weight convolutional neural networks
  authors:
  - Sharif Amit Kamran
  - Khondker Fariha Hossain
  - Joshua Ong
  - Alireza Tavakkoli
  - Andrew G Lee
  publisher: Journal of Vision (ARVO)
  date: '2023-01-01'
  link: https://jov.arvojournals.org/article.aspx?articleid=2792812

- type: paper
  title: A generative adversarial deep neural network to translate between ocular imaging modalities while maintaining anatomical fidelity
  authors:
  - Sharif Amit Kamran
  - Khondker Fariha Hossain
  - Joshua Ong
  - Alireza Tavakkoli
  - Andrew G Lee
  publisher: Journal of Vision (ARVO)
  date: '2022-01-01'
  link: https://jov.arvojournals.org/article.aspx?articleid=2778479
